### ISSUE TITLE
Add video about color

### ISSUE THREAD

**Issue by optozorax** [lhns/awesome-computer-graphics#3]
There is a good video about color in computers: [Computer color is broken](https://www.youtube.com/watch?v=LKnqECcg6Gw). This information can be useful in ray tracing, perhaps it called `gamma correction`.

**Comment by luisdnsantos** [comment]
Video added! [Here's the commit](https://github.com/luisnts/awesome-computer-graphics/tree/45425ac73784b9440820c4234fa52e3fa7a25ade).
